[org/gtk/gtk4/settings/file-chooser]
sort-directories-first=true

[org/gtk/settings/file-chooser]
sort-directories-first=true

[org/gnome/desktop/session]
# Turn off display after 5 minutes
idle-delay=300

[org/gnome/settings-daemon/plugins/power]
# Do nothing when the power button pressed
power-button-action='nothing'
# Disable sleep even if inactive
sleep-inactive-ac-type='nothing'

[org/gnome/desktop/input-sources]
sources=[('xkb', 'us'), ('ibus', 'skk'), ('xkb', 'jp')]
# Disable Caps Lock
xkb-options=['caps:none']

[org/gnome/settings-daemon/plugins/media-keys]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']
[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0]
binding='<Control><Alt>t'
command='wezterm'
name='WezTerm'

[org/gnome/settings-daemon/plugins/color]
night-light-enabled=true
night-light-temperature=3000

[desktop/ibus/general]
preload-engines=['skk']
engines-order=['skk']

[desktop/ibus/engine/skk]
# Enable "Return-key doesn't insert new line on commit"
egg-like-newline=true
# Set initial input mode to 英数 that I use more frequently than the default ひらがな
initial-input-mode=3
